---
name: Release

on:
  push:
    branches:
      - release/*

permissions:
  contents: write
  issues: write

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: false

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Zip Release
        run: git archive --format=zip --output=release.zip HEAD

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@7417b1089e2c7de93510f1901d656ddf60bb024f # v4.7.0
        with:
          versionSpec: '6.4.x'

      - name: Use GitVersion
        uses: gittools/actions/gitversion/execute@7417b1089e2c7de93510f1901d656ddf60bb024f # v4.7.0
        id: gitversion

      - name: Install GitReleaseManager
        uses: gittools/actions/gitreleasemanager/setup@7417b1089e2c7de93510f1901d656ddf60bb024f # v4.7.0
        with:
          versionSpec: '0.20.x'

      - name: Create release with GitReleaseManager
        uses: gittools/actions/gitreleasemanager/create@7417b1089e2c7de93510f1901d656ddf60bb024f # v4.7.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          milestone: ${{ steps.gitversion.outputs.majorMinorPatch }}
          name: 'Release ${{ steps.gitversion.outputs.majorMinorPatch }}'
          assets: |
            release.zip

      - name: Publish release with GitReleaseManager
        uses: gittools/actions/gitreleasemanager/publish@7417b1089e2c7de93510f1901d656ddf60bb024f # v4.7.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          milestone: ${{ steps.gitversion.outputs.majorMinorPatch }}

      - name: Close release with GitReleaseManager
        uses: gittools/actions/gitreleasemanager/close@7417b1089e2c7de93510f1901d656ddf60bb024f # v4.7.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          milestone: ${{ steps.gitversion.outputs.majorMinorPatch }}
